Entrenando... 

/usr/local/lib64/python3.6/site-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
/usr/local/lib64/python3.6/site-packages/torch/nn/functional.py:3328: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/usr/local/lib64/python3.6/site-packages/torch/nn/functional.py:3458: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
/usr/local/lib64/python3.6/site-packages/torch/nn/functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Validando... 

Epoch 0 		 Training Loss: 6.319997051192483e-05 		 Validation Loss: 2.614310823219057e-06
Entrenando... 

Validando... 

Epoch 1 		 Training Loss: 2.0143089202892415e-06 		 Validation Loss: 9.507514226925196e-07
Entrenando... 

Validando... 

Epoch 2 		 Training Loss: 7.21791777068923e-07 		 Validation Loss: 4.717437910528588e-07
Entrenando... 

Validando... 

Epoch 3 		 Training Loss: 3.6012698276907743e-07 		 Validation Loss: 2.7273972904140463e-07
Entrenando... 

Validando... 

Epoch 4 		 Training Loss: 2.7376469081279604e-07 		 Validation Loss: 5.245203405479514e-07
Entrenando... 

Validando... 

Epoch 5 		 Training Loss: 2.2616027955106758e-07 		 Validation Loss: 1.6617635042237567e-07
Entrenando... 

Validando... 

Epoch 6 		 Training Loss: 2.3894324706375524e-07 		 Validation Loss: 1.580763351105574e-07
Entrenando... 

Validando... 

Epoch 7 		 Training Loss: 1.755401530008539e-07 		 Validation Loss: 1.6980349455408826e-07
Entrenando... 

Validando... 

Epoch 8 		 Training Loss: 1.787919330932806e-07 		 Validation Loss: 1.6642633255514738e-07
Entrenando... 

Validando... 

Epoch 9 		 Training Loss: 1.6677527425904904e-07 		 Validation Loss: 5.182001914363355e-06
Entrenando... 

Validando... 

Epoch 10 		 Training Loss: 1.7885793208925087e-07 		 Validation Loss: 1.589771488630376e-07
Entrenando... 

Validando... 

Epoch 11 		 Training Loss: 1.6058567258356023e-07 		 Validation Loss: 1.6254814210414637e-07
Entrenando... 

Validando... 

Epoch 12 		 Training Loss: 1.7431419066633894e-07 		 Validation Loss: 1.5720178546452247e-07
Entrenando... 

Validando... 

Epoch 13 		 Training Loss: 1.635278185544698e-07 		 Validation Loss: 9.015190182253718e-05
Entrenando... 

Validando... 

Epoch 14 		 Training Loss: 1.5524038469861459e-07 		 Validation Loss: 0.016697309743613005
Entrenando... 

Validando... 

Epoch 15 		 Training Loss: 1.606610176863845e-07 		 Validation Loss: 0.697776295542717
Entrenando... 

Validando... 

Epoch 16 		 Training Loss: 1.779908582878747e-07 		 Validation Loss: 1.9392173452814632e-07
Entrenando... 

Validando... 

Epoch 17 		 Training Loss: 1.6562008704285907e-07 		 Validation Loss: 0.002198393389116973
Entrenando... 

Validando... 

Epoch 18 		 Training Loss: 1.7233593318702306e-07 		 Validation Loss: 1.5721863753093145e-07
Entrenando... 

Validando... 

Epoch 19 		 Training Loss: 1.6561793671772238e-07 		 Validation Loss: 1.7228911133315706e-07
Testing... 

Traceback (most recent call last):
  File "CANNet_prueba.py", line 365, in <module>
    output = modelo(x)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "CANNet_prueba.py", line 156, in forward
    x = self.frontend(x)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 254.00 MiB (GPU 0; 23.70 GiB total capacity; 21.70 GiB already allocated; 194.56 MiB free; 21.84 GiB reserved in total by PyTorch)
Proceso finalizado el s√°b may 15 16:19:25 CEST 2021
___________________________________________________
